Feature/second reservatio prototype
nlasagni/fausto-coppi-lab-automation pull request #19
Opened 2021-03-07 23:17 UTC by Giordo94

Sorry for the REALLY BIG PR. We did not expect so many changes.

2021-03-09 20:24 UTC, nlasagni requested changes
Check again (and complete if needed) the javadoc in all classes ;)

2021-03-09 20:24 UTC, nlasagni commented on detektConfig.yml
> +style:
What is the purpose of this settings?

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/MainClass.kt
> +    /* companion object MainClass {
Since i see this is almost an empty class, it can be removed if not needed. Or at least, please remove all the commented code.

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/application/Controller.kt
> +class Controller
I see that this class is not used anywhere. So if you can remove it.

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/infrastructure/CommunicationManagerImpl.kt
> +class CommunicationManagerImpl
I see that this class is not used anywhere. So if you can remove it.

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/application/interfaces/CommunicationManager.kt
> +interface CommunicationManager
I see that this interface is only used by its empty implementation (which indeed is not used). So if you can remove it.

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/presentation/PresenterImpl.kt
> +class PresenterImpl
I see that this class is not used anywhere. So if you can remove it.

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/application/interfaces/Presenter.kt
> +interface Presenter
I see that this interface is only used by its implementation. So if you can remove it.

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/persistence/RepositoryImpl.kt
> +class RepositoryImpl
I see that this class is not used anywhere. So if you can remove it.

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/application/interfaces/Repository.kt
> +interface Repository
I see that this class is only used by its implementation. So if you can remove it.

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/common/ConsultingReservation.kt
> + * @param date The date of the requested consulting
I think that those are @property not @param...

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/entities/events/agenda/AgendaAddConsultingReservationEvent.kt
> +data class AgendaAddConsultingReservationEvent(
Maybe AddAgendaConsultingReservation (without the Event suffix) is better?

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/entities/events/agenda/AgendaAddWorkoutReservationEvent.kt
> +data class AgendaAddWorkoutReservationEvent(
Maybe AddAgendaWorkoutReservation (without the Event suffix) is better?

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/entities/events/agenda/AgendaAddWorkoutReservationEvent.kt
> +    override val id: UUID,
id of what? Maybe a more expressive name could be better?

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/entities/events/agenda/AgendaDeleteConsultingReservationEvent.kt
> +    override val id: UUID,
id of what? Maybe a more expressive name could be better?

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/entities/exceptions/CloseReservationCannotBeUpdated.kt
> +class CloseReservationCannotBeUpdated :
ClosedReservationCannotBeUpdated

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/usecases/CommandReservationUseCase.kt
> +class CommandReservationUseCase(
Maybe this is a too general use case, and creating different use-case classes for each of the functions below could be better

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/usecases/RequestFailedException.kt
> +class RequestFailedException(message: String = "Something really bad happened") : Exception(message)
"Something really bad happened" is not a proper message i think

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/usecases/events/results/RequestSucceededEvent.kt
> + * [Event] representing the failure of a Consulting or Workout reservation.
You wrote here "[Event] representing the failure of a Consulting or Workout reservation." but the class is named RequestSucceededEvent, so?

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/ui/UIManager.kt
> +class UIManager
This is not used, so if you can just remove it.

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/usecases/WorkoutReservationManager.kt
> +    // TODO Probably useless
What is this comment for?

2021-03-09 20:24 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/usecases/WorkoutReservationManager.kt
> +    // TODO Probably useless
This comment "// TODO Probably useless" what is here for?

2021-03-09 21:01 UTC, Giordo94 commented on detektConfig.yml
> +style:
It's needed, otherwise you can have only 2 return in each method. In some cases i needed 3 or even 4 return statements

2021-03-09 21:09 UTC, Giordo94 commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/usecases/events/results/RequestSucceededEvent.kt
> + * [Event] representing the failure of a Consulting or Workout reservation.
Copy and paste is wrong because of this. Fixing asap

2021-03-10 18:07 UTC, nlasagni approved these changes

2021-03-10 21:13 UTC, merged