reservation prototype #3
nlasagni/fausto-coppi-lab-automation pull request #25
Opened 2021-03-15 11:31 UTC by NarcAle

2021-03-15 21:32 UTC, nlasagni requested changes

2021-03-15 21:32 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/entities/reservation/Aim.kt
> +data class Aim(val aim: String) {
Since Aim is the name of the class, can the val be named "value"?

2021-03-15 21:32 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/entities/reservation/FreelancerId.kt
> +class FreelancerId(val freelancerId: UUID) {
Since FreelancerId is the name of the class, can the val be named "value"?

2021-03-15 21:32 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/application/Controller.kt
> +    private val cmd = CommandReservationUseCase(agendaId, ledgerId, eventStore, repository)
"cmd" is a little too short non-meaningful name

2021-03-15 21:32 UTC, nlasagni commented on gradle.properties
> +org.gradle.console=plain
Please remove until there will be sub-projects present

2021-03-15 21:32 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/presentation/Result.kt
> +interface Result
Maybe "Response" is better?

2021-03-16 11:41 UTC, Giordo94 approved these changes, later dismissed
Approved

2021-03-16 11:45 UTC, sbraggion approved these changes, later dismissed

2021-03-16 17:20 UTC, nlasagni requested changes

2021-03-16 17:20 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/application/interfaces/Presenter.kt
> +    fun convertResult(response: Response): String
Maybe "convertResponse" is better?

2021-03-16 17:20 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/entities/reservation/FreelancerId.kt
> +            throw ConsultingReservationFreelancerCannotBeEmpty()
Is this the right exception? How does a FreelancerId know that it is referred to a ConsultingReservation?

2021-03-16 17:20 UTC, nlasagni commented on src/main/kotlin/it/unibo/lss/fcla/reservation/domain/entities/reservation/Aim.kt
> +            throw WorkoutReservationAimCannotBeEmpty()
Is this exception right? How does the Aim know that it refers to a WorkoutReservation?

2021-03-16 20:13 UTC, nlasagni approved these changes

2021-03-16 20:30 UTC, merged