Feature/fcla 92 split project into subprojects
nlasagni/fausto-coppi-lab-automation pull request #26
Opened 2021-03-16 10:19 UTC by sbraggion

2021-03-16 20:22 UTC, nlasagni requested changes

2021-03-16 20:22 UTC, nlasagni commented on build.gradle.kts
> +            // Otherwise it throws a "No main manifest attribute" error
This maybe should be placed above line 38?

2021-03-16 20:22 UTC, nlasagni commented on build.gradle.kts
> +            // Include all of its dependencies inside our application
This is already included in the comment at line 47?

2021-03-16 20:22 UTC, nlasagni commented on build.gradle.kts
> +                // configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
Is this commented line still useful?

2021-03-16 20:22 UTC, nlasagni commented on build.gradle.kts
> +            // To add all of the dependencies otherwise a "NoClassDefFoundError" error
This comment has no useful meaning, maybe should be changed properly.

2021-03-18 16:50 UTC, nlasagni submitted a review, later dismissed

2021-03-18 21:22 UTC, Giordo94 commented on reservation/src/main/kotlin/it/unibo/lss/fcla/reservation/domain/entities/exceptions/ConsultingReservationFreelancerCannotBeEmpty.kt
> +package it.unibo.lss.fcla.reservation.domain.entities.exceptions
This is the old version. Delete it

2021-03-18 21:22 UTC, Giordo94 commented on reservation/src/main/kotlin/it/unibo/lss/fcla/reservation/domain/entities/exceptions/ClosedReservationCannotBeUpdated.kt
> +package it.unibo.lss.fcla.reservation.domain.entities.exceptions
This is the old version. Delete it

2021-03-18 21:23 UTC, Giordo94 commented on reservation/src/main/kotlin/it/unibo/lss/fcla/reservation/domain/entities/exceptions/WorkoutReservationAimCannotBeEmpty.kt
> +package it.unibo.lss.fcla.reservation.domain.entities.exceptions
This is the old version. Delete it

2021-03-18 21:26 UTC, Giordo94 commented on reservation/build.gradle.kts
> +val myMainClass = "it.unibo.lss.fcla.MainClassKt"
Main class was renamed. Please update with "it.unibo.lss.fcla.reservation.InteractiveReservationMicroserviceStarterClassKt"

2021-03-18 21:26 UTC, Giordo94 requested changes
Some small fix needed

2021-03-18 21:33 UTC, Giordo94 approved these changes
Approved

2021-03-18 21:45 UTC, merged