Feature/fcla 98 consulting prototype #2
nlasagni/fausto-coppi-lab-automation pull request #33
Opened 2021-03-30 13:18 UTC by sbraggion

2021-03-31 19:27 UTC, nlasagni requested changes

2021-03-31 19:27 UTC, nlasagni commented on consulting/src/main/kotlin/it/unibo/lss/fcla/consulting/application/controllers/IController.kt
> +    fun execute(request: IRequest)
No documentation for this fun?

2021-03-31 19:27 UTC, nlasagni commented on consulting/src/main/kotlin/it/unibo/lss/fcla/consulting/application/controllers/FreelancerController.kt
> +                else -> TODO()
TODO?

2021-03-31 19:27 UTC, nlasagni commented on consulting/src/main/kotlin/it/unibo/lss/fcla/consulting/application/controllers/ConsultingController.kt
> + * This is a concrete implementation of [BaseController]. This class take the requests
[BaseController]?

2021-03-31 19:27 UTC, nlasagni commented on consulting/src/main/kotlin/it/unibo/lss/fcla/consulting/application/controllers/FreelancerController.kt
> + * This is a concrete implementation of [BaseController]. This class take the requests
[BaseController]?

2021-03-31 19:27 UTC, nlasagni commented on consulting/src/main/kotlin/it/unibo/lss/fcla/consulting/application/persistence/ConsultingRepository.kt
> +package it.unibo.lss.fcla.consulting.application.persistence
Is this the right package for a clean architecture? Maybe the repository should be put into a "adapter" package? See for example here https://github.com/carlphilipp/clean-architecture-example or here https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html

2021-03-31 19:27 UTC, nlasagni commented on consulting/src/main/kotlin/it/unibo/lss/fcla/consulting/application/presentation/IResponse.kt
> + * Interface that each response must implement
"Interface that each response must implement", but "each response" of what? :)

2021-03-31 19:27 UTC, nlasagni commented on consulting/src/main/kotlin/it/unibo/lss/fcla/consulting/application/persistence/EventStore.kt
> +package it.unibo.lss.fcla.consulting.application.persistence
Same question made for ConsultingRepository.

2021-03-31 19:27 UTC, nlasagni commented on consulting/src/main/kotlin/it/unibo/lss/fcla/consulting/application/persistence/FreelancerRepository.kt
> +package it.unibo.lss.fcla.consulting.application.persistence
Same question made for ConsultingRepository.

2021-03-31 19:27 UTC, nlasagni commented on consulting/src/main/kotlin/it/unibo/lss/fcla/consulting/application/presentation/IRequest.kt
> + * Interface that each request must implement
"Interface that each request must implement", but "each request" of what? :)

2021-03-31 19:27 UTC, nlasagni commented on consulting/src/test/kotlin/it/unibo/lss/fcla/consulting/FreelancerControllerTest.kt
> +class FreelancerControllerTest : FreeSpec({
Maybe this test should be removed?

2021-03-31 19:27 UTC, nlasagni commented on consulting/src/test/kotlin/it/unibo/lss/fcla/consulting/MockPresenter.kt
> +class MockPresenter : IPresenter {
No documentation for this class?

2021-03-31 19:27 UTC, nlasagni commented on consulting/src/main/kotlin/it/unibo/lss/fcla/consulting/usecases/IPresenter.kt
> +    fun onResult(result: BaseFacade)
No documentation for these fun?

2021-03-31 19:33 UTC, Giordo94 submitted a review, later dismissed
Approved

2021-04-01 07:32 UTC, sbraggion commented on consulting/src/main/kotlin/it/unibo/lss/fcla/consulting/application/presentation/IRequest.kt
> + * Interface that each request must implement
each request of anything :)

2021-04-01 13:22 UTC, nlasagni approved these changes

2021-04-01 13:32 UTC, merged